/* eslint-disable */
// Enhanced — bilingual copy
// FR is the source of truth (brief is in French). EN mirrors the same tone.

const COPY = {
  fr: {
    // ----- Landing -----
    landing: {
      title: "Pitche ton idée produit.\nOn la transforme en draft PRD challengé.",
      placeholder: "Décris l'idée en quelques phrases. Aussi vague soit-elle. On la remettra en forme.",
      cta: "Lancer le cadrage",
      cta_caret: "ou enregistre une note vocale",
      hint: "Sans compte. Tu ne signes qu'après la première reformulation.",
      what_it_is: "Ce qu'Enhanced fait",
      what_it_is_body: "Reformule ton idée en problème utilisateur, identifie ce qui est prouvé, ce qui ne l'est pas, et ce qu'il faudra démontrer avant d'écrire la première ligne de code.",
      what_it_isnt: "Ce que ce n'est pas",
      what_it_isnt_body: "Pas un outil de backlog. Pas un générateur de specs. Pas un dashboard. Enhanced vit avant tous ces outils.",
      examples_label: "Quelques drafts récents, partagés publiquement",
      footer: "enhanced.pm · pour les équipes qui veulent builder moins de mauvaises features",
    },

    // ----- Wizard chrome -----
    wizard: {
      step_labels: ["Cadrage du problème", "Validation par la data", "Challenge des risques", "Draft finalisé"],
      step_short: ["Cadrage", "Data", "Risques", "Draft"],
      progress: "Étape",
      autosaved: "Sauvegardé · il y a 4 s",
      back: "Retour",
      next: "Continuer",
      finish: "Voir le draft final",
      signup_gate_title: "Ta première reformulation est prête.",
      signup_gate_body: "Crée ton compte pour sauvegarder ce draft et continuer le cadrage. 30 secondes.",
      signup_gate_cta: "Créer mon compte",
      signup_gate_skip: "Continuer sans compte (perdable)",
    },

    // ----- Conversation (step 1: cadrage) -----
    step1: {
      ai_intro: "Avant tout — je reformule. Ton message est court, l'idée est plutôt formulée comme une solution (« je veux ajouter ___ »). Je vais essayer de la recadrer en problème utilisateur, et te demander de valider.",
      ai_voicequote_lead: "Tu as dit :",
      voicequote: "Je veux ajouter une fonctionnalité de recherches sauvegardées pour que les power users arrêtent de perdre leurs filtres entre deux sessions.",
      ai_reformulation_lead: "Reformulation en First Use Case :",
      reformulation: "Je suis un power user de l'onglet Insights, et quand je reviens le matin sur l'app, ce qui compte c'est de retrouver instantanément la vue filtrée que j'avais hier — mais en réalité tous mes filtres sont reset, et donc je dois refaire 5 à 6 clics avant de voir les bons chiffres.",
      ai_confirm_q: "Cette reformulation te paraît juste ?",
      ai_after_confirm: "Bien. Une dernière chose avant de passer à la data — à quel OKR ou priorité company cette idée se rattache ?",
      ai_explain_why: "Je pose cette question parce qu'une feature qui n'est pas rattachée à une priorité explicite finit toujours en orpheline dans le backlog.",
      // ask_user options
      confirm_options: ["Oui, c'est juste", "Reformule", "Précise"],
      okr_options: ["Activation des power users", "Rétention semaine 4+", "Conversion vers tier_pro", "Réduction du churn enterprise", "Autre — préciser"],
    },

    // ----- Step 2: validation data -----
    step2: {
      ai_intro: "Pour valider l'hypothèse « les power users perdent leurs filtres et ça les freine », il y a trois choses qu'on aimerait pouvoir mesurer. Je te les donne — tu réponds avec ce que tu sais déjà, ce que tu peux aller chercher, ou ce qui n'existe pas encore.",
      ai_data_intro: "Trois signaux qui changeraient ma conviction :",
      data_signals: [
        { tag: "evidence", title: "Fréquence de retour sur l'onglet Insights filtré", how: "PostHog · funnel session_open → filter_apply, fenêtre 90j, segment tier_pro" },
        { tag: "evidence", title: "Taux de re-saisie des mêmes filtres dans une session", how: "Mixpanel · property filter_combination_hash répété en < 90s" },
        { tag: "assumption", title: "Friction perçue (verbatims, tickets, NPS)", how: "Recherche tickets « filtre », interviews 5 utilisateurs tier_pro" },
      ],
      ai_followup: "Tu en as déjà regardé certains ?",
      tools_options: ["PostHog", "Mixpanel", "Amplitude", "Heap", "Aucun outil analytics", "Autre — préciser"],
      ai_after_tools: "Bien. Décris ce que tu as vu — chiffres exacts si tu les as, ressenti à défaut. Tout ira dans le PRD, taggé selon le niveau de preuve.",
      user_answer: "Sur Mixpanel j'ai vu que 4.2x par session ils ouvrent la vue filtrée. Je n'ai pas le taux de re-saisie des mêmes filtres, c'est à mesurer. Sur le ressenti je n'ai aucun ticket support qui mentionne « filtre perdu » sur 90 jours.",
      ai_after_answer: "Noté. J'ai ajouté dans le PRD : 1 signal confirmé, 1 à mesurer, 1 contradiction faible. La contradiction (0 ticket support) mérite d'être posée — soit les users s'y sont habitués, soit ce n'est pas la friction que tu crois.",
    },

    // ----- Step 3: challenge des risques -----
    step3: {
      ai_intro: "On arrive au moment où je te pousse. Quatre risques fondamentaux à scorer. Je te donne mon analyse pour chacun, tu acceptes ou tu pousses back. À la fin, score de confiance global + reco.",
      risks: [
        {
          key: "value",
          name: "Valeur",
          question: "Les users vont-ils réellement s'en servir ?",
          ai_take: "Signal Mixpanel solide (4.2x/session). Mais ouverture ≠ usage répété d'une feature de sauvegarde. Confiance modérée.",
          score: 3,
        },
        {
          key: "usability",
          name: "Utilisabilité",
          question: "Sauront-ils s'en servir ?",
          ai_take: "Pattern « save view » archi-connu (Notion, Airtable, Linear). Risque faible si l'UI suit ces conventions.",
          score: 4,
        },
        {
          key: "feasibility",
          name: "Faisabilité",
          question: "L'équipe peut-elle le builder ?",
          ai_take: "ENG-2104 a été classé Won't do en 2024 — il y a un historique à comprendre. À discuter avec Théo avant le scoping.",
          score: 2,
        },
        {
          key: "viability",
          name: "Viabilité business",
          question: "Ça fonctionne pour l'entreprise ?",
          ai_take: "Aligné sur l'OKR activation tier_pro. Pas de coût opérationnel récurrent. Risque très faible.",
          score: 4,
        },
      ],
      ai_overall: "Score de confiance global : 64 / 100. Le plus gros caillou c'est la faisabilité (ENG-2104) et secondairement la valeur (une preuve manque).",
      ai_recommendation_lead: "Ma reco — pas autoritaire, tu restes décisionnaire :",
      recommendation: "Tester d'abord avant de builder. Spécifiquement : ship « auto-remember last filter » derrière un flag tier_pro pendant 2 semaines, mesure le retention et le verbatim, puis décide. Coût : ~2j d'eng. Tu apprends la valeur sans toucher à la faisabilité.",
      reco_options: ["Builder maintenant", "Tester d'abord", "Abandonner", "Reformule la reco"],
      ai_push_back_hint: "Pas d'accord avec un score ? Clique dessus pour le pousser ou ajouter ton contre-argument.",
    },

    // ----- Step 4: draft final -----
    step4: {
      ai_intro: "Le draft est prêt. Tu peux l'affiner par re-prompt sur n'importe quel block — passe la souris dessus, clique sur Refine, et dis-moi ce qui doit changer en langage naturel.",
      ai_review_q: "On valide tel quel ou tu veux affiner avant de partager ?",
      review_options: ["Valider le draft", "Affiner un block", "Repartir d'une étape précédente"],
      ai_share_help: "Quand tu valides, je génère un lien public lecture-seule (enhanced.pm/p/…) et un PDF brandé Enhanced. Pas de Word, pas de ticket — Enhanced vit avant ces outils.",
    },

    // ----- PRD document -----
    prd: {
      draft_label: "Draft",
      version: "v1",
      generated_from: "généré depuis ton pitch",
      auto_save: "sauvegarde auto",
      title: "Recherches sauvegardées pour les power users",
      subtitle: "Une manière pour les power users de conserver leurs combinaisons de filtres entre les sessions, pour qu'ils arrêtent de refaire le même setup chaque matin.",
      section_problem: "Problème utilisateur (First Use Case)",
      section_assumed: "Hypothèses implicites",
      section_data: "Contexte data",
      section_evidence_found: "Signal confirmé",
      section_evidence_missing: "Aucune preuve trouvée",
      section_evidence_todo: "À mesurer avant de builder",
      section_risks: "Évaluation des 4 risques",
      section_confidence: "Score de confiance global",
      section_recommendation: "Notre recommandation",
      section_success: "Critères de succès",
      section_kill: "Kill criteria",
      section_next: "Prochaines étapes",
      tag_evidence: "Evidence",
      tag_assumption: "Assumption",
      tag_to_verify: "To verify",
      refine_cta: "Refine ce block",
      refine_placeholder: "Décris ce qui doit changer. Ex : raccourcis, ajoute le contexte B2C, sois plus direct sur le risque viabilité.",
      refine_examples: ["Raccourcis", "Ajoute le contexte B2C", "Plus direct sur la viabilité"],
      refine_submit: "Regénérer",
      refine_cancel: "Annuler",
      streaming_marker: "Enhanced écrit…",
    },
  },

  en: {
    landing: {
      title: "Pitch your product idea.\nWe turn it into a challenged PRD draft.",
      placeholder: "Describe the idea in a few sentences. As vague as you like. We'll reshape it.",
      cta: "Start scoping",
      cta_caret: "or record a voice note",
      hint: "No account needed. You only sign up after the first reformulation.",
      what_it_is: "What Enhanced does",
      what_it_is_body: "It reframes your idea as a user problem, surfaces what's proven, what isn't, and what you'd need to show before writing a line of code.",
      what_it_isnt: "What it is not",
      what_it_isnt_body: "Not a backlog tool. Not a spec generator. Not a dashboard. Enhanced lives before all of those.",
      examples_label: "Recent drafts shared publicly",
      footer: "enhanced.pm · for teams that want to ship fewer bad features",
    },
    wizard: {
      step_labels: ["Frame the problem", "Validate with data", "Challenge the risks", "Final draft"],
      step_short: ["Frame", "Data", "Risks", "Draft"],
      progress: "Step",
      autosaved: "Saved · 4 s ago",
      back: "Back",
      next: "Continue",
      finish: "See final draft",
      signup_gate_title: "Your first reformulation is ready.",
      signup_gate_body: "Create your account to save this draft and continue scoping. 30 seconds.",
      signup_gate_cta: "Create my account",
      signup_gate_skip: "Continue without account (will be lost)",
    },
    step1: {
      ai_intro: "First — I'm reframing. Your message is short, and the idea is phrased as a solution (\"I want to add ___\"). Let me try to recast it as a user problem and have you confirm.",
      ai_voicequote_lead: "You said:",
      voicequote: "I want to add a saved-searches feature so power users stop losing their filters between sessions.",
      ai_reformulation_lead: "Reframed as a First Use Case:",
      reformulation: "I'm a power user of the Insights tab, and when I come back the next morning, what matters is to find instantly the filtered view I had yesterday — but in reality all my filters are reset, so I have to redo 5 to 6 clicks before I see the right numbers.",
      ai_confirm_q: "Does that reframing feel right?",
      ai_after_confirm: "Good. One last thing before we move to data — which OKR or company priority does this hook into?",
      ai_explain_why: "I'm asking because a feature that isn't tied to an explicit priority always ends up orphaned in the backlog.",
      confirm_options: ["Yes, that's right", "Rephrase", "Refine"],
      okr_options: ["Activate power users", "Week 4+ retention", "Conversion to tier_pro", "Reduce enterprise churn", "Other — specify"],
    },
    step2: {
      ai_intro: "To validate \"power users lose their filters and it slows them down\", there are three things we'd want to measure. I'll lay them out — you answer with what you already know, what you can pull, or what doesn't exist yet.",
      ai_data_intro: "Three signals that would move my conviction:",
      data_signals: [
        { tag: "evidence", title: "Return rate on the filtered Insights view", how: "PostHog · session_open → filter_apply funnel, 90d window, tier_pro segment" },
        { tag: "evidence", title: "Same-session filter re-entry rate", how: "Mixpanel · property filter_combination_hash repeated in < 90s" },
        { tag: "assumption", title: "Perceived friction (verbatims, tickets, NPS)", how: "Search support tickets for \"filter\", 5 user interviews on tier_pro" },
      ],
      ai_followup: "Have you already looked at any of these?",
      tools_options: ["PostHog", "Mixpanel", "Amplitude", "Heap", "No analytics tool", "Other — specify"],
      ai_after_tools: "Good. Describe what you saw — exact numbers if you have them, qualitative gut if not. Everything goes in the PRD, tagged by proof level.",
      user_answer: "On Mixpanel I saw 4.2x per session they open the filtered view. I don't have the same-session re-entry rate, that's to measure. On the qualitative side: zero support tickets mentioning \"lost filter\" in 90 days.",
      ai_after_answer: "Noted. I added to the PRD: 1 confirmed signal, 1 to measure, 1 weak contradiction. The contradiction (0 support tickets) deserves to be flagged — either users got used to it, or it's not the friction you think.",
    },
    step3: {
      ai_intro: "Now the part where I push you. Four fundamental risks to score. I'll give my read on each — you accept or push back. At the end, a global confidence score and a recommendation.",
      risks: [
        { key: "value", name: "Value", question: "Will users actually use it?", ai_take: "Mixpanel signal is solid (4.2x/session). But opening a view ≠ repeated use of a save feature. Moderate confidence.", score: 3 },
        { key: "usability", name: "Usability", question: "Will they know how to use it?", ai_take: "\"Save view\" pattern is well-trodden (Notion, Airtable, Linear). Low risk if UI follows those conventions.", score: 4 },
        { key: "feasibility", name: "Feasibility", question: "Can the team build it?", ai_take: "ENG-2104 was marked Won't do in 2024 — there's history to understand. Discuss with Théo before scoping.", score: 2 },
        { key: "viability", name: "Business viability", question: "Does it work for the company?", ai_take: "Aligned with tier_pro activation OKR. No recurring operational cost. Very low risk.", score: 4 },
      ],
      ai_overall: "Global confidence: 64 / 100. The biggest hurdle is feasibility (ENG-2104), with value as a secondary gap (one proof is missing).",
      ai_recommendation_lead: "My recommendation — not authoritative, you stay in charge:",
      recommendation: "Test first before building. Specifically: ship \"auto-remember last filter\" behind a tier_pro flag for 2 weeks, measure retention and verbatims, then decide. Cost: ~2d of eng. You learn the value without touching feasibility.",
      reco_options: ["Build now", "Test first", "Abandon", "Rephrase reco"],
      ai_push_back_hint: "Disagree with a score? Click it to push back or add your counter-argument.",
    },
    step4: {
      ai_intro: "The draft is ready. You can refine any block via re-prompt — hover the block, click Refine, and tell me what should change in plain language.",
      ai_review_q: "Ship as is, or refine before sharing?",
      review_options: ["Validate draft", "Refine a block", "Go back to a previous step"],
      ai_share_help: "When you validate, I generate a read-only public link (enhanced.pm/p/…) and a branded PDF. No Word, no ticket — Enhanced lives before those.",
    },
    prd: {
      draft_label: "Draft",
      version: "v1",
      generated_from: "generated from your pitch",
      auto_save: "auto-saved",
      title: "Saved searches for power users",
      subtitle: "A way for power users to persist filter combinations across sessions, so they stop redoing the same setup every morning.",
      section_problem: "User problem (First Use Case)",
      section_assumed: "Implicit assumptions",
      section_data: "Data context",
      section_evidence_found: "Confirmed signal",
      section_evidence_missing: "No evidence found",
      section_evidence_todo: "To measure before build",
      section_risks: "4-risk evaluation",
      section_confidence: "Global confidence score",
      section_recommendation: "Our recommendation",
      section_success: "Success criteria",
      section_kill: "Kill criteria",
      section_next: "Next steps",
      tag_evidence: "Evidence",
      tag_assumption: "Assumption",
      tag_to_verify: "To verify",
      refine_cta: "Refine this block",
      refine_placeholder: "Describe what should change. E.g.: make shorter, add B2C context, be more direct on viability risk.",
      refine_examples: ["Make shorter", "Add B2C context", "More direct on viability"],
      refine_submit: "Regenerate",
      refine_cancel: "Cancel",
      streaming_marker: "Enhanced is writing…",
    },
  },
};

window.ENHANCED_COPY = COPY;
